---
title: "R Stuff"
author: "Jessica Minnier"
date: '`r Sys.Date()`'
output:   
  github_document:
    toc: yes
---


```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(skimr)
library(janitor)
library(jmmisc)
#### Global chunk options -----------------------------

knitr::opts_chunk$set(
  eval       = TRUE,    # whether to run code in code chunk
  include    = TRUE,    # whether to include the chunk output
  echo       = FALSE,   # Whether to show code chunk in final output
  error      = TRUE,    # whether to display error messages
  message    = FALSE,   # whether to preserve messages
  warning    = FALSE,   # whether to preserve warnings
  comment    = "#>",    # a character string to append at start
                        # of each line of results in final document
  tidy       = FALSE,   # whether to tidy code chunks for display
  dpi        = 96, 
  fig.width  = 6,       # consistent width for figures
  fig.asp    = 0.618,   # the golden ratio, can be adjusted in individual chunks
  out.width  = "100%",   # controls the output size
  fig.align  = "center" # give plot room to breathe
)
```

# r markdown

- tabs: `## title {.tabset .tabset-fade}` in tab header ([stack overflow q](https://stackoverflow.com/questions/38062706/rmarkdown-tabbed-and-untabbed-headings))

# visualization

## palettes

- studio gihbli palettes [ewenme/ghibli](https://github.com/ewenme/ghibli)

```{r}
#install.packages('ghibli')

# see palette names and colours
par(mfrow=c(9,3))
for(i in names(ghibli::ghibli_palettes)) print(ghibli::ghibli_palette(i))

```

## ggplot themes

- ggthemes

# data summary

- `skimr` package
- `summarytools` [dcomtois/summarytools](https://github.com/dcomtois/summarytools)

```{r, results='asis'}
#install.packages("devtools")
library(summarytools)
dfSummary(iris, plain.ascii = FALSE, style = "grid")
```

## data dictionary

- [Jennifer Thompson's Data Dictionary example](https://gist.github.com/jenniferthompson/1e6059569214807bbc7db472ff117442)
